### ISSUE TITLE
module :mbcs is not available

### ISSUE THREAD

**Issue by BlindingDark** [woxtu/elixir-mbcs#3]
when I try to use
```elixir
Mbcs.start
```
It's show
```
** (UndefinedFunctionError) function :mbcs.start/0 is undefined (module :mbcs is not available)
    :mbcs.start()
```
other function also cause same error `module :mbcs is not available`

Is there some dependent lib I need？

**Comment by woxtu** [comment]
Sorry for delayed response. I'll check it.

**Comment by woxtu** [comment]
This module contains GitHub dependencies and Hex ignores it.
So you have to add the module like this:

```elixir
{:elixir_mbcs, github: "woxtu/elixir-mbcs", tag: "0.1.3"}
```

Sorry, I didn't know that until now.
